### ISSUE TITLE
Add Option to Select Steam Original Assets

### ISSUE THREAD

**Issue by MattyXarope** [SteamGridDB/decky-steamgriddb#10]
Unfortunately, some games don't have any custom artwork which causes a blank screen when attempting to add art from the database. 

Seen here with "Burnhouse Lane":

![download (12)](https://user-images.githubusercontent.com/30245871/208326049-93bb1a77-1efe-4e94-af09-3b62068d6bd9.jpeg)

However, this game - like others - has Steam original assets available on SteamGrid. It would be ideal to be have an option to select the default Steam assets for all artwork of a particular game.

Other than a case for a game with no custom artwork, this feature could be useful for those users who use default Steam artwork, but want to then customize one or two pieces of art for the game.

**Comment by gilest** [comment]
As a workaround to this I've been uploading original assets as custom artwork manually on Steam Grid DB.

Use case – Steam Next Fest demos often don't have grid images.

**Comment by gilest** [comment]
> This is against the site rules. Please read them: https://www.steamgriddb.com/help#asset-removal-1

Ah thanks for letting me know – I'll remove the uploaded assets.
