### ISSUE TITLE
Allow vertical capsules to be shown in the Wide Capsule tab's filter settings. [Feature Request]

### ISSUE THREAD

**Issue by Pleasance13** [SteamGridDB/decky-steamgriddb#110]
A theme for the _CSS Loader_ Decky plugin called _Edit Featured Banner_ reshapes the wide capsule of the most recently played game on the Deck's home screen. It cannot, however, change the art asset used. If vertical grids were able to be filtered on in the Wide Capsule tab, they could be used with this CSS theme.

Wide Capsule when used with _Edit Featured Banner_
![steamuserimages-a akamaihd](https://github.com/SteamGridDB/decky-steamgriddb/assets/108769327/440ace03-a1ee-4c21-b71b-1e23b1116fa8)

Vertical Capsule when used with _Edit Featured Banner_ (manually replaced in files)
![7_screenshots_20240608144914_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/108769327/3b339816-f21b-4625-925f-62e8706599c7)

**Comment by doZennn** [comment]
Instead of this hack, I've added a proper way to make the recently played game render the same component as the rest: 5d345b1d390d5e74ee864b211e7124d607e2c567

![image](https://github.com/user-attachments/assets/13824c9e-d245-4c42-9ecb-985ec5b81fc2)
