### ISSUE TITLE
File system is not refreshed for manual replacement

### ISSUE THREAD

**Issue by liartes** [SteamGridDB/decky-steamgriddb#12]
To reproduce :
-Install the Decky plugin
-Try to browse the file location for a non steam game
-Go to desktop mode and prepare a folder in the Pictures folder with some arts
-Back to gaming mode
-On the Manage tab in the plugin, the filesystem tree does not make the new folder appear

I tried to reboot the deck, no changes.

**Comment by doZennn** [comment]
Can you see it if you manually type in the path?

**Comment by doZennn** [comment]
This seems to be an issue with the [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) file picker. I already plan to submit a PR with a better file picker with more features than the current one they have, I'll keep this issue open until that's done.

**Comment by doZennn** [comment]
Fixed in https://github.com/SteamGridDB/decky-steamgriddb/commit/677857c5688002fd9bb4af54a23945194f312fa8
