### ISSUE TITLE
"Failed to download icon" on non-Steam games

### ISSUE THREAD

**Issue by coolpringles** [SteamGridDB/decky-steamgriddb#121]
Every asset will download and apply fine except for icons, which gives an error in the corner: ``There was a problem applying this asset. Failed to download icon from https://cdn2.stea...``
This is an issue with every non-Steam game that I've tried. Steam games have a different issue but don't give an error about failing to download, only saying that the icon was applied when it wasn't.
## 
Decky version 2.12.3
SteamGridDB version 1.5.0-loaderv2
SteamOS version 3.5.19

**Comment by Mappsnet7** [comment]
Same for me on the latest stable version

**Comment by MNarath1** [comment]
might be nothing but i noticed that all icons in question were transparent png's

**Comment by DisasterIncarnate** [comment]
seems to only affect non-steam games, rolling back to plugin version 1.4.0 works.
