### ISSUE TITLE
Resize covers to 300x450 instead of 600x900?

### ISSUE THREAD

**Issue by KibaGasteiz** [SteamGridDB/decky-steamgriddb#13]
The library isn't as responsive as it could, and sometimes the covers need to load (only for 0.1 secs or something).

I'm just wondering here, shouldn't be faster with low quality images? Because the Deck resolution is 1280x800 and it can't show 600x900 covers in all their glory to begin with.

Is there any way to test if a gallery of 300x450 images can boost the performance of the library, and if this is true... shouldn't we use imagemagick for every downloaded cover to set it at a lighter resolution?

If everything i'm saying has no sense please mark this as closed, thanks!

**Comment by doZennn** [comment]
The deck UI actually uses virtualized lists to render library pages, so library games (and their images) are not rendered at all if they're out of view. Images outside of view. So covers are not going to be slowing things down much.

Your idea does make sense though but imo not needed and transforming images is out of scope for this project.
