### ISSUE TITLE
Unclosable fullscreen blur after failing to find capsules (rare)

### ISSUE THREAD

**Issue by TsukikoChan** [SteamGridDB/decky-steamgriddb#14]
Use case - AfterParty installed as nonsteam game (from epic, using epiclauncher from desktop), change artwork.
Try to browse for capsule, nothing appears if wifi is being weird (see steamdeck 5ghz wifi bug after sleep).

Since nothing appears, it times out, but the page overlays over the steamdeck OS completely, very blurry but you can see unreachble "refresh" button and a line of text before it. No means of closing the unreachable webpage, restart of SD fixes it.
Cannot reproduce as restart also fixed 5ghz connection issue so change artwork actually shows capsule art now.

**Comment by doZennn** [comment]
Can you give SteamOS details and client branch?  
Also the the exact name of the shortcut would help with debugging. Thanks!

**Comment by doZennn** [comment]
Still can't seem to reproduce it, think i might be getting the timing wrong. Would you be able to record a video?
