### ISSUE TITLE
Can't overwrite images from games added by Heroic Launcher

### ISSUE THREAD

**Issue by rlach** [SteamGridDB/decky-steamgriddb#15]
I have some games added to steam trough Heroic Game Launcher "Add to Steam" functionality. For those games I can find steamgrid images with this plugin, and when I choose an image I get notification that it was successful. But the images are not actually applied.

There is workaround for it. If I use Manage tab to delete the images first and then choose my new images it will all work as intended. I suspect that deleting the originals from the code before setting up new images might fix the issue.

Steps to reproduce:
* Install any game trough heroic(there are some free games on gog https://www.gog.com/partner/free_games ) (Ideally a game that has some data in steamgrid)
* In heroic go into installed game details -> 3 dots in upper right -> Add to Steam
* Restart Steam client/steam deck so the library refreshes with a new game
* Find the game -> properties -> Change artwork...
* Set capsule/wide capsule/hero/logo, wait for success notification (don't use icon, since it will want to restart steam deck)
* Look into Manage tab or close the plugin 

Expected: the selected images are displayed
What happens: the originals are displayed

**Comment by danivalls** [comment]
Same with games added by EmuDeck

**Comment by CorneliousJD** [comment]
This shows fixed 1 month ago but this is still an issue for me - has this fix not been merged yet?

**Comment by TimetoPretend54** [comment]
> This shows fixed 1 month ago but this is still an issue for me - has this fix not been merged yet?

+1 For this issue still being an issue.

**Comment by doZennn** [comment]
1.0.1 was just a hotfix for a crash on the new Steam client version. Other fixes and features will be available next minor.
