### ISSUE TITLE
Can't switch tabs from Capsules

### ISSUE THREAD

**Issue by schrammalama** [SteamGridDB/decky-steamgriddb#16]
After I change two or three game artworks all of a sudden I can switch between artwork tabs and can only apply Capsule artwork. Restarting fixes it until I do two or three more then it breaks.

**Comment by doZennn** [comment]
Can't seem to reproduce this

**Comment by DisasterAreaDesigns** [comment]
I'm having the same issue.  Could it be an interaction with another plugin, perhaps?

I'm currently running
FlatpakUpdater 1.0.3
Emuchievements 2.0.0-5bff...
MeetaDeck 1.0.0
TabMaster 1.0.0-ebd8...
vbrantDeck 1.3.1
Free Games 1.0.0

Uninstalling TabMaster seems to fix the issue with SteamGridDB.

**Comment by doZennn** [comment]
Confirmed a TabMaster problem. Leaving this open until the author fixes it.
