### ISSUE TITLE
Manually Define Game Title Search

### ISSUE THREAD

**Issue by AngelAbaddon** [SteamGridDB/decky-steamgriddb#20]
For games where there are multiple versions (Final Fantasy VIII and Remastered in my example case), it would be useful to have the option to manually define the title to search for an alternate version of the game, as they may have far more options for artwork.

**Comment by doZennn** [comment]
You can search for games from the filters (X)

**Comment by AngelAbaddon** [comment]
Just seen on the front page screenshot that should be the case but looks like I'm running into a bug then as my filter options start with Dimensions - there's no Game option available. Checked across numerous games and it's the case for all of them. I'm running DeckOS 3.4.4 Stable, Decky v2.4.5 Stable and SteamGridDB 1.0.0 (latest available option on Decky).

**Comment by doZennn** [comment]
Oh i see now, you can currently only do it on non-Steam shortcuts. Should be easy to implement for the next release.
