### ISSUE TITLE
Viewable Grid Limit

### ISSUE THREAD

**Issue by Alberios** [SteamGridDB/decky-steamgriddb#21]
If selected filter options would return more than 50 potential results, only the first 50 are shown.  There is no indication of any further available options, nor any way to load the omitted options without altering filter settings.

Sorry if this is intended behavior; I couldn’t find documentation one way or the other.

**Comment by Alberios** [comment]
This issue may be from steamgriddb itself.  I noticed that BoilR has the same issue.  It too returns exactly 50 results regardless of if the game has more.

**Comment by doZennn** [comment]
https://github.com/SteamGridDB/decky-steamgriddb/commit/edc50ee35e618fce391207bee1a5d39206beb311
