### ISSUE TITLE
Plugin shows images for the previously selected game in certain situations

### ISSUE THREAD

**Issue by rlach** [SteamGridDB/decky-steamgriddb#22]
Sometimes the plugin shows images for the previous game that was selected. For example select Batman -> Change Artwork... and you'll see images for Batman. Then go to Spider-man -> Change Artwork... and sometimes you'll see the art for Batman instead of Spider-man. I'm not sure for all things that cause it.

Steps to reproduce:
Unfortunately I didn't manage to find one reliable way to reproduce it. Whenever I think I found a way, next time I try it it's not breaking. I think it's related to higher cpu or storage activity. This works... sometimes:
* start downloading any game with few gigs of size (so it doesn't finish too fast)
* go into your library and "options -> change artwork..." on multiple games. 
* In some cases older game will appear instead of the current one

Interestingly enough when you click options the menu for the game will display proper title for the game, so Steam Deck itself catches proper game. But I think the hook for the plugin is too late to notice the menu. Sometimes it unloads the "Change option..." option after a while, but doesn't replace it with the new game.

"Just don't download games while changing artwork" doesn't fully work, because activity caused by changing artwork also seems to cause the issue. When you do it the plugin downloads new art, and then library loads the downloaded art, and I think this makes the issue appear as well. Downloading game is just more reliable in making the plugin unreliable.

**Comment by Pepelespooder** [comment]
I'm Getting the same issue with Having to back out and select a game a second time to get it to show the proper game. I have a feeling I never noticed it happening until I used an animated capsule, Could coincide with an update, But I use a decent amount of animated capsules and experience it Every time now. No sometimes about it. Every time I go to open a game to change the artwork unless on fresh restart it polls the old games info.

**Comment by rlach** [comment]
Yeah, once it happens it usually sticks until system restart and then it happens for every game. But I'm not sure what causes the first breakage.

You might be on to something with animated capsules. It started happening to me regularly since I've started using animated capsules. My friend says he has been experiencing it since the plugin was published(according to him it never worked for him properly), and he had animated capsules already (got them trough one of automated steamgrid tools).

**Comment by Pepelespooder** [comment]
I think it might be something to do with animated capsules Holding up the storage or something in the background while loading in. Some capsules will have delays well loading in up to like 5 seconds that their just a blank image. Thinking maybe while its doing that is possibly holding some hook in the background essentially in an active state

**Comment by DJScias** [comment]
Hello there.

Still noticing this issue today in the following form:
- Click change artwork on capsule (library view) first time after reboot works fine.
- Another game capsule change shows me the previous.
- Doing it again finally shows the right game.

It sort of feels like it takes two change artworks invocation before it passes the right info. But that's how it works for me. Invoking the option twice on a capsule will search the right images.
