### ISSUE TITLE
The plugin is not working anymore on steam deck

### ISSUE THREAD

**Issue by tooonyo** [SteamGridDB/decky-steamgriddb#26]
Version : 1.0.0
I manage to install the plugin via the "decky shop".
When I click on SteamGridDB, I have the folowwing error :

TypeError : Cannot read property 'prototype' of undefined
at eval (eval at importReactPlugin (http://localhost:l337/frontend/index.js:1874:43), <anonymous>:25864:55)

It doesn't work anymore for me

**Comment by Aev69** [comment]
Same error here.

**Comment by dismas82** [comment]
Same here

**Comment by tooonyo** [comment]
If I open the "beta" store, I can download a newer version that partially
works. It doesn't detect all the games and is very slow.

**Comment by SlightlyPeckish** [comment]
> 

This worked I just changed the store channel to testing installed steamgriddb update 1.0.1-acfd9c2 then swapped the store channel back to default

**Comment by dismas82** [comment]
That worked for me! Thanks a lot!!

**Comment by doZennn** [comment]
#25
