### ISSUE TITLE
Manage Images does not show all relevant file types.

### ISSUE THREAD

**Issue by AsamiImako** [SteamGridDB/decky-steamgriddb#33]
When manually selecting an image from the Manage section (e.g. if say SteamGridDB doesn't have an image and you want to add your own) only .jpg file types show, you are unable to select other file types such as .png for logos or .ico for icons, etc.

**Comment by doZennn** [comment]
What version of the plugin are you using?

**Comment by AsamiImako** [comment]
1.0.1 which seems to be the latest version available on the store. Apologies if this is already fixed but not yet released.

**Comment by doZennn** [comment]
No worries, this is fixed already in 1.1.0 and should release soon.
