### ISSUE TITLE
Translated and Fixed some strings in the Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by ThomasEricB** [SteamGridDB/decky-steamgriddb#36]
@doZennn Saw your post on Reddit asking for people to contribute on Crowdin, so I decided to revise the current Brazilian Portuguese translation and translate the missing strings. Please accept the two revisions I modified. Thank you. 

By the way, this is my profile on SteamGridDB: https://www.steamgriddb.com/profile/76561198051799142

**Comment by doZennn** [comment]
Thank you, what name do you want me to use for credit?

**Comment by ThomasEricB** [comment]
> Thank you, what name do you want me to use for credit?

Thomas Eric would be fine.
