### ISSUE TITLE
Just doesn't do anything.

### ISSUE THREAD

**Issue by metya** [SteamGridDB/decky-steamgriddb#55]
I installed the latest stable version 1.2.4 and it doesn't work. After I click the "change artwork" button there is just a blank Steam store page. I've tried reinstalling or installing older versions - nothing works. 

Have the latest decky loader and the latest stable steam version and OS.

**Comment by AltKrypto** [comment]
Same problem here

**Comment by thanitos** [comment]
Same issue here, 
Decky 2.8.0-pre3
SteamGridDB 1.2.4
Steam O.S 3.4.6 build 20230313.1
No errors just opens to your library with nothing loaded.

**Comment by thanitos** [comment]
Issue is now resolved, uninstalling Decky and installing Decky from their GitHub fixed GridDB and storage cleaner which also failed to load

**Comment by metya** [comment]
Indeed! It just works!
@thanitos thank you!) 🎊

**Comment by metya** [comment]
Ha! But now I can't install any new plugins :))

But it's not about this plugin.

**Comment by thanitos** [comment]
> Ha! But now I can't install any new plugins :))
> 
> But it's not about this plugin.

I went into Decky, uninstalled all my apps, uninstalled Decky with the installer, deleted the old version I had and downloaded the latest version, reinstalled then installed all my apps. I also used the stable version and the default store
