### ISSUE TITLE
Keeps loading

### ISSUE THREAD

**Issue by Echarnus** [SteamGridDB/decky-steamgriddb#59]
Each time I want to assign a picture to something it's as if the filter is just not loading. It's in an eternal loading screen.

**Comment by vload** [comment]
I have the same issue

**Comment by qfoxb** [comment]
Bump

**Comment by benediktniedernhuber** [comment]
I'm experiencing endless loading screens when trying to change the artwork as well.

**Comment by doZennn** [comment]
Can you all try again on the newest update? And does it happen all the time?

**Comment by vload** [comment]
It is working now for me.

**Comment by benediktniedernhuber** [comment]
It's still endlessly loading for me on version 1.3.0

**Comment by doZennn** [comment]
This isn't a SGDB issue or a plugin issue, the Deck seems to be sensitive to network configurations with weird DNS setups and ipv6.
