### ISSUE TITLE
Clean Gameview Hero Art Alignment Compatibility Issues

### ISSUE THREAD

**Issue by cammyfan3** [SteamGridDB/decky-steamgriddb#60]
Clean Gameview stretches the hero art to fit the screen, cutting out some of the artwork.  SteamGridDB centers artwork, resulting in artwork with subjects on the sides to appear cut off.  Examples:
![20230719133954_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/119364018/38d1f86a-cb77-455a-974c-aa8c7358d683)
![20230719134155_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/119364018/5d0b0842-6bf6-466a-9ab2-4834ce296b34)
![20230719134206_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/119364018/8e027f7b-abff-4ada-9d18-1e35a3db9105)

It should also be noted that this issue also occurs on the home page both without plugins, and when I am using the expanded Hero option in Art Hero.  Tony Hawk used for examples:
(Face cut off)
![20230719141131_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/119364018/c40bcec9-ea14-4356-8d5b-c797e93d2a30)
(Only negative space visible)
![20230719141237_1](https://github.com/SteamGridDB/decky-steamgriddb/assets/119364018/74140b39-5fac-451a-9742-12ce2d58bd5e)

An option to choose a center or move and resize the artwork in these cases would be greatly appreciated.  Since it may affect alignment, I am also using Footer Editor to remove my footer.

**Comment by doZennn** [comment]
This plugin doesn't alter any CSS, this is most likely a problem with Clean Gameview.

**Comment by cammyfan3** [comment]
No CSS editing is necessary if the image is cropped on either side with Clean Gameview's dimensions and aspect ratio in mind.  I think this would be a much easier solution that going through both SteamDB AND Clean Gameview (who would still need to code this in) every time a game's art is improperly displayed.  Also, this problem occurs without the use of Clear Gameview, as illustrated above with Tony Hawk's Project 8.
