### ISSUE TITLE
 menus disappearing

### ISSUE THREAD

**Issue by ravage007** [SteamGridDB/decky-steamgriddb#61]
so I just got in to this because I like adding a lot of third-party non-steam games and this is a great way to find artwork but I have to play Rush to collect the menu every time I try to change artwork or add artwork to a game example video below

Unless a video only link
https://youtu.be/ZmJJ8sQcVd0

**Comment by doZennn** [comment]
This is a known problem and can't be fixed at the moment. Best workaround is to either quickly close and open the menu abd try again or do it from the cog from within the main game page: 
![image](https://github.com/SteamGridDB/decky-steamgriddb/assets/10759579/8db516be-6865-4576-b6b4-67328c138ac3)
