### ISSUE TITLE
How-to contribute

### ISSUE THREAD

**Issue by twjasa** [SteamGridDB/decky-steamgriddb#68]
Hello 👋 

Excellent tool! I would like to contribute but I don't see an md file that explains how to. Also, I'm curious how functions are tested and debugged.

Thanks!

**Comment by doZennn** [comment]
Best way to start is by getting the [SteamDeckHomebrew/decky-plugin-template](https://github.com/SteamDeckHomebrew/decky-plugin-template) up and running in your dev environment first and reading the [wiki](https://wiki.deckbrew.xyz/en/user-guide/home#plugin-development).
Once you're familiar enough, working on this plugin won't be much different.
