### ISSUE TITLE
Steamos 3.5 Broken

### ISSUE THREAD

**Issue by superboo07** [SteamGridDB/decky-steamgriddb#70]
Option to change artwork disappeared when updating to steamos 3.5 making the plugin unusable
![image](https://github.com/SteamGridDB/decky-steamgriddb/assets/39241538/fbde531a-82d6-41b1-810e-ea6e1be5fd49)

**Comment by daft-goose** [comment]
Confirmed, I'm seeing this too. Thought it was an issue with decky loader but after uninstalling and reinstalling still seeing this problem

**Comment by robertjawoods** [comment]
This is still broken for me. Steam OS 3.5, SteamGridDB 1.3.1 @doZennn
