### ISSUE TITLE
Menu option disappeared 

### ISSUE THREAD

**Issue by chiriesz** [SteamGridDB/decky-steamgriddb#73]
I still have Steamgriddb installed but the menu option to change artwork has disappeared. I've tried uninstalling and reinstalling the plugin but it remains missing.

**Comment by MateuszG** [comment]
Same problem

**Comment by Doombringerson** [comment]
Same problem, it's like it's not even installed.

**Comment by 123ika** [comment]
Also happening to me, using version 3.5.1 of Steam OS. Reinstalling does not help

**Comment by craigz** [comment]
i just updated the plug-in to version 1.3.0-77a2ff0 and the menu no longer appears. it had been working with Steam OS 3.5.1 prior to installing the update, which i believe happened yesterday (10.13.2023).

**Comment by 123ika** [comment]
> i just updated the plug-in to version `1.3.0-77a2ff0` and the menu no longer appears. it had been working with Steam OS 3.5.1 prior to installing the update, which i believe happened yesterday (10.13.2023). **update**: i switched the store channel to `default` which promptly offered version `1.3.1` (newer then testing?) which i installed and it is again working as expected.

Can confirm changing to default channel also makes it work for me, thanks!

**Comment by krompus** [comment]
I've been on the Default store channel since the beginning, and I've noticed that the "Change Artwork..." menu entry never shows the first time I open the little "gear" menu, but if I close the menu and open it again (sometimes need to do it a couple of times) the button appears, very strange.

**Comment by craigz** [comment]
> ...if I close the menu and open it again (sometimes need to do it multiple times) the button appears, very strange.

this is consistent with how it's worked for me for some time now. rarely the option appears on the first time.

**Comment by Doombringerson** [comment]
> I've been on Steam Deck Stable and Decky's Default store channel since the beginning, and I've noticed that the "Change Artwork..." menu entry never shows the first time I open the ⚙️ menu, but if I close the menu and open it again (sometimes need to do it multiple times) the button appears, very strange.

Damn, that actually works. I've gone through and tried different games before, but never opened and closed the same game several times. Guess this will have to do for now.

**Comment by krompus** [comment]
> Damn, that actually works. I've gone through and tried different games before, but never opened and closed the same game several times. Guess this will have to do for now.

You don't need to close the game itself or even leave the game page: just open, close and reopen the ⚙️ menu on the game page to reveal the "Change Artwork..." button. It seems to "remember" which games you've done this to per session, and show the button from then on until you reboot.

**Comment by doZennn** [comment]
This is now fixed and released in v1.3.3.

**Comment by krompus** [comment]
Sorry, issue persists on v1.3.3
