### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by sheffeyG** [SteamGridDB/decky-steamgriddb#88]
I am trying to develop a plugin, and I learned the openFilePickerV2 api from your work (thanks), But I'm having some difficulty when I assign the return value to a variable and try to refresh the ui，and I noticed the way you [refreshOverview](https://github.com/SteamGridDB/decky-steamgriddb/blob/ef501013c76fc4a97a2dbb2d5ecd46abedb236d0/src/components/plugin-pages/ManageTab.tsx#L30), lol. so is the problem from serverapi or just my [code ](https://github.com/sheffeyG/CheatDeck/blob/890bac2d1b580bbf30b143171e695623ea04fd8e/src/component/Content.tsx#L26C8-L26C8)broken?

**Comment by doZennn** [comment]
`refreshOverview()` is a hack to force an apps overview cache to reload, i don't think that's what you want to do. Your code seems fine, I'm assuming you want `showPath` to change?

**Comment by sheffeyG** [comment]
@doZennn thanks for your reply, and that is the problem I [met ](https://github.com/sheffeyG/CheatDeck/issues/2#issue-2028333357)
