### ISSUE TITLE
Only loads first page

### ISSUE THREAD

**Issue by lithiumfox** [SteamGridDB/decky-steamgriddb#95]
I noticed that on the website there are a LOT more choices than what we get from the plugin. It appears that there isn't an ability to pull paginated results? Not sure if this is limited by the API itself or just an oversight.

**Comment by lithiumfox** [comment]
https://github.com/SteamGridDB/decky-steamgriddb/issues/21 Looks like it was related to this one, and it's back. An example because it has so many is Cyberpunk 2077, which cuts off at the second row of Page 2

![image](https://github.com/SteamGridDB/decky-steamgriddb/assets/4545555/eb543b68-a830-427b-b9b5-5c3a07223a33)
![image](https://github.com/SteamGridDB/decky-steamgriddb/assets/4545555/51f14f26-b32e-4812-8629-556768c92d95)

**Comment by Nidor87** [comment]
I still experience this issue with it only loading 50 assets tried on 2 steam decks reinstalled plugin, nothing changed still only loads 50 in v. 1.4.0.
